### ISSUE TITLE
Parser lib for tree

### ISSUE THREAD

**Issue by justinvdk** [ProgrammingLife2016/PL2-2016#13]
Thomas suggested not reinventing the wheel on parsing the newick format.
I've come accros: http://olduvai.sourceforge.net/ but this library raises an exception when run with the 340tree.rooted.TKK.nwk file

Havn't come across any promising (java!) libraries for newick file parsing

**Comment by justinvdk** [comment]
jar provided on this page:
https://c13s.wordpress.com/2013/02/07/a-lightweight-javacc-newick-parser/

raises a similar exception? The .nwk file seems valid as it is properly rendered on http://etetoolkit.org/treeview/

**Comment by wouterjsmit** [comment]
Maybe ask the other groups? Group 5 was in Drebbelweg an hour ago

**Comment by justinvdk** [comment]
Found the issue in the parser. It doesn't understand the scientific notation of the numbers.
Interpets 0.0123e-01 as 0.0123 and than "e-01" which doesn't make sense to him.

Incidentally the Geex group used exactly the same parser, and forked the same library I found here: https://github.com/qurben/libnewicktree with the needed changes to parse nwk files using scientific notation.

Thanks Geex!
