### ISSUE TITLE
use of libnewicktree in gui

### ISSUE THREAD

**Issue by justinvdk** [ProgrammingLife2016/PL2-2016#14]
@FarisElghlan See c847a38a302014ed827c8bcfe3799295e72f81b5. 
This commit includes a simple implementation of your interface, and changes in Dnav.java to parse the .nwk file in resources (also added in this commit).

Does this work as expected? I do think there is room for improvement but for next Friday this will have to do. For now the class is a sloppy implementation to bridge between the models used by us and by the library, we should take a look and make them more compatibly. (For ex. without changing the library we can't implement the 'getChildIndex' method.)

**Comment by justinvdk** [comment]
I realise I got the graph/tree mixed up so disregard the comment in-code about index versus id.

**Comment by FarisElghlan** [comment]
In the main class (Dnav) you use a class called NWKReader:
import nl.tudelft.pl2016gr2.parser.controller.NWKReader;
but this class is not present in that package. I have changed this to GFAReader and it now works fine.
The getchildindex method is only used for the animation when zooming out. I have however managed to fix this in a pretty easy/nice way (without reflection): I wrote an equals method and used the getChild(int) method to loop over all children to find the index.
The rest of the interface is implemented as intended, so you can create a pull request.

**Comment by justinvdk** [comment]
PR created, see #15
