### ISSUE TITLE
Application needs heatmap/visualizaton of the drug resitance

### ISSUE THREAD

**Issue by wouterjsmit** [ProgrammingLife2016/PL2-2016#142]

**Comment by wouterjsmit** [comment]
This information is available through functionality in #165

**Comment by FarisElghlan** [comment]
I think we should actually use the heatmap thought. It is hard to create a description for many heatmaps in the tree, but I think a possible solution would be to use a small amount of the vertical space of the tree to add around 2 comboboxes with a descriptive name and a line below the tree and give the user the option to choose what kind of heatmap he wants to see. The following image is a sketch of what I think would be a nice way to show multiple heatmaps:
![tree](https://cloud.githubusercontent.com/assets/9753699/15801844/e11a4e48-2aa1-11e6-9479-8eb9d0109ae3.png)
