### ISSUE TITLE
GenomeMap exception

### ISSUE THREAD

**Issue by FarisElghlan** [ProgrammingLife2016/PL2-2016#145]
The GenomeMap throws an exception if a given ID is not present in the map. For the phylogenetic tree this is not desireable, because the tree sometimes contains more genomes than the graph. A null value should be returned in this case.

**Comment by wouterjsmit** [comment]
@FarisElghlan Could you not use a try-catch structure? That's how exception normally are handled.

Unless it is meant to be common, then obv `null` is more logical.

**Comment by FarisElghlan** [comment]
Similar things like the 'HashMap' class also return null in case the id is not found

**Comment by wouterjsmit** [comment]
Fair enough, I'll make sure to change it.

**Comment by wouterjsmit** [comment]
The `GenomeMap` currently does not throw errors when trying to get non-existent strings, fixing this issue.

On this matter, `null`-checks, or rather: the possibility of `NPE`s should be avoided.

There should be a solution that has to be implemented once in the code (such as in the parser), and then  removing the need for this check.
See #172
