### ISSUE TITLE
Drag and drop should work on whole tree selection

### ISSUE THREAD

**Issue by wouterjsmit** [ProgrammingLife2016/PL2-2016#160]
Currently it only works on the exact node.
With the highlight box, it is very feasible and clear to drag from that whole box.

**Comment by FarisElghlan** [comment]
I think it is not intuitive to drag from the area around the tree node. The user of the application must be aware of the fact that he is dragging a node of the tree. This would could also cause a slight misclick to drag a different node than was intended.
I did however change the nodes in the tree, first the 2nd circle around the node was not dragable, maybe that caused usability issues for you.

**Comment by FarisElghlan** [comment]
Closing this if there is no response within 3 days.

**Comment by wouterjsmit** [comment]
@FarisElghlan Sounds like a good alternative. could you PR that version or something so I can check it out?

**Comment by FarisElghlan** [comment]
Pretty sure it's on dev already

**Comment by wouterjsmit** [comment]
Great, it is a lot more interactive now. Closing this.
