### ISSUE TITLE
GraphNode must offer trim() method to ensure minimal usage of resources

### ISSUE THREAD

**Issue by wouterjsmit** [ProgrammingLife2016/PL2-2016#168]
Currently, the `addInEdge(GraphNode)` and `addOutEdge(GraphNode)` do not correctly minimize the memory usage in the underlying data structure. For this reason they are deprecated.

However, adding / removing edges is a rather useful operation.

The GraphNode interface should provide functionality to support this, while also minimizing data and optimizing performance.

Options.
- [x] Implement `trimToSize()` used by the caller of the `addEdge()` methods
- [x] Implement `addAll(Collection<GraphNode>)` which adds all elements and then trims automatically (more performance, less clean code for caller)

**Comment by FarisElghlan** [comment]
We should probably keep both options, but use the 2nd one whenever possible. Could you make sure that everywhere in the code where the add function is used the trim method is also called before you close this issue?
