### ISSUE TITLE
Genomes that are not present in one of the data sets cause bugs

### ISSUE THREAD

**Issue by wouterjsmit** [ProgrammingLife2016/PL2-2016#172]
The genomes should be either removed at parse-time, or some other solution has to be found.

We cannot have the application crash left and right because the data sets differ.

**Comment by FarisElghlan** [comment]
In my opinion we should just remove everything of the metadata/tree which is not in the graph This is probably the easiest solution.

**Comment by wouterjsmit** [comment]
The Programming Life team did mention that sometimes, the tree (or metadata) is not available. We should take this into account in finding a solution.

The base line should therefore always be the graph. If data (a genome) is in the graph, it must be available in the application, even though there might not be a node for it in the tree.

The other way around, I think the most desired solution is graying out parts of the meta/tree that are not available in the graph.

Removing the data from the tree requires a little more thought: When removing elements we might break the phylogeny.

**Comment by FarisElghlan** [comment]
Filtered the non-existing phylogenetic tree genomes out of the tree. The same is done for the annotation and metadata file.
