### ISSUE TITLE
Fix graph comparison

### ISSUE THREAD

**Issue by FarisElghlan** [ProgrammingLife2016/PL2-2016#179]
Currently the comparison of two graphs is broken because of bugs which occur with the bubbles. This must be fixed.

**Comment by wouterjsmit** [comment]
Possibly relevant: #169.

I will work on that bug, hopefully by tomorrow morning it should be fixed (first have to do some other tasks).

**Comment by FarisElghlan** [comment]
I meant the ability to draw 2 graphs above each other, which is currently disabled

**Comment by wouterjsmit** [comment]
I understood, but maybe the comparison breaks more when the unbubbled graph is presented with wrong edges. So if that's the case, it is relevant :)

**Comment by FarisElghlan** [comment]
Fixed, see: 8cc6cc9eab3a565c8ea38347b06651b36ec1a220
