### ISSUE TITLE
Show lineage in main overview

### ISSUE THREAD

**Issue by wouterjsmit** [ProgrammingLife2016/PL2-2016#183]
The lineages must be shown on the main overview. This gives a great general overview of what is where.

To complete this tasks, a few points must be considered.
- There can be many lineages, and nodes in the graph can contain very many of them. In the overview, the colours can be impeding. Blending is most likely not an option (at least, not the ultimate solution), because the user must be able to find the desired lineage. When it is blended with 10 others, he cannot find the one colour he is looking for.

With the client, a few options were discussed.
1. Be able to toggle the lineages in the graph.
2. Only show the largest few lineages (top 5 for instance)
3. Only show the most prominent lineage going through a specific node/edge (majority vote of all genomes through the node/edge)

In the optimal scenario, all of these features are possible. It is desirable to show at least one or two , so that the client can decide to fully implement them in the next sprint.

The first task therefore will consist of the following.
- [ ] Create image of only largest lineages
- [ ] Create image of most prominent lineage per node
- [ ] save the code for possible implementation in next sprint

**Comment by FarisElghlan** [comment]
I am not sure what you mean by "Create image of ...". I thought we would just color the edges between the nodes according to the lineages with a few options to turn off certain lineages.

**Comment by wouterjsmit** [comment]
@FarisElghlan I meant that at least showing an image is enough to satisfy the client. There's no need for a complete implementation. But if you can do that, that's great of course.
