### ISSUE TITLE
Search result selection highlighting in Tree cannot be unselected

### ISSUE THREAD

**Issue by wouterjsmit** [ProgrammingLife2016/PL2-2016#193]
When selecting nodes via the search results, the tree edges leading to those nodes light up.

However, I cannot seem to unselect all nodes (at most I can select just one). If I hide the search pane the selection persists.

**Comment by justinvdk** [comment]
You can ctrl+click on a row to deselect it. I would agree that some proper way of clearing is better but that would be a feature, not a bugfix imho.
