### ISSUE TITLE
Split graph in subgraphs to show in visualizer

### ISSUE THREAD

**Issue by wouterjsmit** [ProgrammingLife2016/PL2-2016#24]
- [ ] Subgraph nodes should be a new object instantiation rather than a reference to the same object (objects should be copied)
- [ ] Nodes in the subgraph, even though they are copies, should use the exact same ID as in the main graph
- [ ] More specifically, the only thing that may differ for these nodes is the `genome list`, the `inLinks` and the `outLinks`, because some elements of these lists may not be present in the subgraph.
- [ ] The algorithm will require an `OriginalGraph` and a list of genomes that should be present in the subgraph. It returns a new instantiation of `OriginalGraph` that only contains nodes for the specified genomes, with only links between these nodes.

**Comment by wouterjsmit** [comment]
Because this sprint has been very short due to Ascension Day and the documentation deadlines, and because the next presentation to the client is only next week, there is no direct need to close this right now

**Comment by wouterjsmit** [comment]
@cathmer @FarisElghlan 
- Merged nodes (bubbles) in either graph that have the same contents should get the same ID.

Note that the requirement of giving merged nodes the same ID should be honoured in the Bubbling algorithm, because the splitting algorithm only deals with `OriginalGraphs` and does not even know about bubbling.

I suggest that, as far as this is relevant, the bubble ID should be based on the `amount of nodes in the bubble` and `the sum of the IDs of the nodes`. This makes sure that
- IDs are unique
- IDs are the same if the bubbles are the same because the splitting algorithm will copy node IDs.

One downside of this method is that the IDs are not necessarily in ascending order. If this is problematic, some other solution must be found.

**Comment by wouterjsmit** [comment]
@FarisElghlan As far as I managed to optimize my algorithm so far, it consists of the following structure:

**Adding nodes**
- Create new OriginalGraph
- For each desired genome, traverse the graph over the genome path, adding every original node on the way

**Pruning paths**
- The nodes in the OriginalGraph now are the same objects as in the original, this poses two problems: nodes are direct references into the original graph and the links (edges) are incorrect
- A pruning step creates a new OriginalGraph and adds a copy of the node (Node constructor with arguments from the original node). The in/out links of this node are iterated over and **only** added to the copy if the link is in the set of Nodes that was found in the previous step. Same goes for genome list

The algorithm requires two separate steps, because it would be impossible to determine whether a link that is currently not in the subgraph will be added later. Therefore one must determine the in/out links after all nodes are found. This is quite doable because of the hashmap data structure in OriginalGraph

**Comment by FarisElghlan** [comment]
> I suggest that, as far as this is relevant, the bubble ID should be based on the amount of nodes in the bubble and the sum of the IDs of the nodes. This makes sure that
> -  IDs are unique
> -  IDs are the same if the bubbles are the same because the splitting algorithm will copy node IDs.

This doesn't ensure an ID is unique. For example, if graph 1 skips nodes 3-6 (doesn't have any path through them) and combines bubbles 2 and 7 nad graph 2 combines nodes 4 and 5, both graphs have a bubble with the same ID (9), while they are not equal

**Comment by wouterjsmit** [comment]
> both graphs have a bubble with the same ID (9), while they are not equal

You are right, although you did not factor in the bubble size (2). Since this is equal for both that still doesn't work however.

You did suggest earlier using an Array ID. I agree that this should be beneficial, althoug the splitting algorihtm does not deal with this, but the bubbling algorithm (BubbleGraph) should implement some type `< ? extends Node>` which deals with Array IDs.

**Comment by wouterjsmit** [comment]
Finished but requires code review and more testing. Will not be part of the demo for milestone 3 (it does not add anything meaningful to the working version, because it is backend and there is no front end to support it).
