### ISSUE TITLE
Improve performance + vertical position

### ISSUE THREAD

**Issue by FarisElghlan** [ProgrammingLife2016/PL2-2016#259]
Improve the performance of the bubbling algorithms and try to improve the vertical position at least a little bit.

Estimated effort: 1 day.

**Comment by wouterjsmit** [comment]
What are your ideas for this?

**Comment by FarisElghlan** [comment]
For the performance I will run a profiler and check what can possibly be improved in the bubbling algorithms.
For the vertical position I will try to give paths with more genomes more vertical space, since they will have more mutations.

I combined these into one issue because I wanted to make 3 tasks which will take 1 day each (since we have 3 days left before the deme video has to be finished).

**Comment by wouterjsmit** [comment]
Sounds good

**Comment by FarisElghlan** [comment]
Performance fix done, see #260

**Comment by FarisElghlan** [comment]
Done, see #260 for performance and #262 for vertical alignment
