### ISSUE TITLE
Dev Build is failing because of style warnings

### ISSUE THREAD

**Issue by wouterjsmit** [ProgrammingLife2016/PL2-2016#29]
The dev should start passing builds asap.

**Comment by FarisElghlan** [comment]
Currently fixed the style warnings for the gui module on my branch. You can expect the gui (and probably also launcher) modules to pass on dev soon (when I finish everything which is needed for my next pull request).
Not sure about the other modules though.

**Comment by wouterjsmit** [comment]
Fixed by #37
