### ISSUE TITLE
Find and Setup C project management tools

### ISSUE THREAD

**Issue by wouterjsmit** [ProgrammingLife2016/PL2-2016#3]
These tools should cover similar functionality to PMD, FindBugs, Checkstyle and code coverage.
In addition, additional C specific tools that check for memory management should be part of the build process
- [ ] Find clean way to build C lib during building process
- For all platforms
- Least possible IDE setup
- [ ] Testing framework
- [ ] Design smells
- [ ] Memory Leakage (Valgrind)
- [ ] Style rules
- [ ] Code coverage

**Comment by justinvdk** [comment]
Closing for now. Opening when (re)considering C as language to build parser in.
