### ISSUE TITLE
Travis setup should be rebased into all local branches

### ISSUE THREAD

**Issue by wouterjsmit** [ProgrammingLife2016/PL2-2016#30]
All branches that are currently active should rebase onto `dev`, which now contains the work from #23 
Rebasing updates the branch to include all current changes in `dev`, but avoids a merge commit, making the branch cleaner.
Branches that need rebasing:
- [x] feature/tree-graph-integration
- [x] feat/semantic-zooming 
- [x] findBubbles

This is done by the following two commands:

```
git checkout <your-branch>
git fetch origin
git rebase origin/dev
```

**Comment by wouterjsmit** [comment]
Accidentally typed the rebase command for `origin/master`. This should be `origin/dev`. I edited the main post

**Comment by FarisElghlan** [comment]
I merged dev into "feature/tree-graph-integration" and fixed all of the style warnings.
