### ISSUE TITLE
Checkstyle adjustments

### ISSUE THREAD

**Issue by FarisElghlan** [ProgrammingLife2016/PL2-2016#34]
Currently got 2 problems with checkstyle:
1. Checkstyle currently doesn't seem to check for maximum method length.
2. Checkstyle complains about multiple variable declarations on the same line, for example:
    double d1, d2;
    is wrong and must be changed to:
    double d1;
    double d2;
    In my opinion the first option is better, because it is shorter and still easy to read.

**Comment by wouterjsmit** [comment]
[The SUN Java convention](http://www.oracle.com/technetwork/java/javase/documentation/codeconventions-141270.html#2992) is to use one declaration per line.

However, I personally am a fan of multiple declarations, as I think variables should be self-documenting (which is encouraged with the rather strict naming conventions for variables by PMD and Checkstyle).

I opened a a PR #36 with the integration of the MaximumMethodLength module.

If others agree, I will also remove the MultipleVariableDeclarations modules (to allow multiple variables on one line).

**Comment by FarisElghlan** [comment]
As stated in my first post I agree with removing the MultipleVariableDeclarations rule, but I guess that comment was intended for the other people in the group. Maybe tell them via whatsapp to post their opinion on this rule here?

**Comment by cbilstra** [comment]
I agree that multiple variable declarations should be possible.

**Comment by justinvdk** [comment]
For Java I too think it should be possible.
I think devs are anxious because in C it can get tricky with multi variable declaration in combination with pointers.
