### ISSUE TITLE
Travis builds take very long to compile

### ISSUE THREAD

**Issue by wouterjsmit** [ProgrammingLife2016/PL2-2016#40]
This is most likely caused by downloads.

This is suboptimal and it should be looked into whether there is some low hanging fruit that speeds up the builds.

**Comment by wouterjsmit** [comment]
Project management in general already took too much work. Moving this to the backlog instead

**Comment by FarisElghlan** [comment]
Can this be closed? Don't think its worth looking into this anymore, since the project is nearly completed.
