### ISSUE TITLE
Data is too big to load into memory and requires some streaming process

### ISSUE THREAD

**Issue by wouterjsmit** [ProgrammingLife2016/PL2-2016#41]
The data sets will soon no longer fit into main memory at once.

For this reason, there should be an API that can preprocesses the data and can serve parts of it to the GUI (application) when it requires them.

**Comment by wouterjsmit** [comment]
First attempts using SQLite were unsuccesful. Sprint 4 will be dedicated to this.

**Comment by wouterjsmit** [comment]
The need for this heavily declined during sprint 4, because of much more efficient algorithms and data structures throughout the application (see #82),  coupled with sickness means that less time was spent on this than initially planned. First version can be found at #100, but is not integrated into release 4.

**Comment by wouterjsmit** [comment]
Because of immense memory optimization (~90% reduction), memory is less of an issue, if at all. Until the Programming Life organization provides us the 6000 genome data set, there is no need for implementing such an infrastructure.
Additionally, the organization explicitly asked us not to implement this.

**Comment by FarisElghlan** [comment]
Can be closed?
