### ISSUE TITLE
Source code needs more coverage

### ISSUE THREAD

**Issue by wouterjsmit** [ProgrammingLife2016/PL2-2016#44]
Currently coverage is very low.

This neesd to be fixed for current code, and generally kept up to date for all pull requests.

**Comment by FarisElghlan** [comment]
Working on the GUI tests. See: #59 for the progress.

**Comment by wouterjsmit** [comment]
All modules except for the following contain at least sufficient (75%+) line coverage
- Launcher
- Shared (only coverage is from 3rd party, which will be excluded soon)

**Comment by FarisElghlan** [comment]
The shared module is tested at: #63
The launcher module doesn't have to be unit tested (as described in the testing document). In the future we might test it with integration tests though.
