### ISSUE TITLE
Create product planning

### ISSUE THREAD

**Issue by wouterjsmit** [ProgrammingLife2016/PL2-2016#5]
The planning should provide an overview of all milestones.

**Comment by wouterjsmit** [comment]
File found here:
https://docs.google.com/document/d/1VflGE0ozLgNkNuLLqJIzJp_E0oySQ8kIwVhUJP2lvHI/edit#heading=h.qztzykb2u2gi

The first milestones look good. However, I would argue that the step from a small data set to the 6000 sequences is a single step (single week). To support such sizes, we cannot incrementally improve our platform, but have make a drastic (algorithmic / architectural) change that lowers the time complexity dramatically. If we are spending many weeks full-time on improving this step by step, we should take a step back and look at the feasibility of the current path we're taking instead.

I would propose that we move the loading of 6000 is moved to around halfway (milestone 4/5). The later weeks we could then focus on improving or expanding the views (making the visualization algorithms work for larger data sets and adding different functionalities to the views, such as filters, selections, or completely new views)

Additionally, we should probably write these documents in `LaTeX`, although a draft obviously has no need for that yet.

**Comment by cbilstra** [comment]
Hmm, I do not agree with that. Ofcourse we can reach those milestones earlier, but I think this is a good schedule to work with. We can adjust the milestones, but I think that the adjustment should then be that earlier milestones are moved to a later week instead. I think loading 6000 DNA sequences in week 5 is not realistic, looking at the previous year.

**Comment by wouterjsmit** [comment]
I agree that it is going to be difficult. However, I think that we will not at all be able to achieve the 6000 sequences goal if we're still struggling with this after the first half.
On further thought, I would say that reaching 6000 is much more important than having more views. Seeing that this first goal is indeed very difficult, we might push additional views and visualization tools to the 'future work' area

**Comment by wouterjsmit** [comment]
@thomasabeel mentioned in last week's meeting that we should implement an iterative prototyping design. He concluded that we should squash the first three weeks into one, and then leave more time for reaching 6000 strands.

**Comment by wouterjsmit** [comment]
Moved to Milestone 2 since final deadline is only this Wednesday
