### ISSUE TITLE
Test GUI

### ISSUE THREAD

**Issue by FarisElghlan** [ProgrammingLife2016/PL2-2016#59]
Test the following classes of the GUI. Animations and visual positions don't have to be tested.
- [x] ViewNode
- [x] DrawGraph
- [x] TreeManager
- [x] SelectionManager
- [x] NodeDensityHeatmap
- [x] AnimationEvent
- [x] Area
- [x] DescriptionPane
- [x] TextDescription
- [x] HeatmapManager
- [x] GraphicsChangedEvent

**Comment by FarisElghlan** [comment]
Done.
![coverage](https://cloud.githubusercontent.com/assets/9753699/15126077/9e5e10ec-1630-11e6-9786-c401c168f9ec.png)
RootLayout is annoying to test, because it is initialized by JavaFX (using reflection) and it only initializes other classes. This class will be tested using integration tests in the future.
PhylogeneticTree should be moved to a different package, so I didn't test it yet.
All of the other missing test coverage is mainly because of animations which I will not test.

**Comment by cbilstra** [comment]
@FarisElghlan looks good, nice argumentation on why some classes are not (fully) tested
