### ISSUE TITLE
Create product vision

### ISSUE THREAD

**Issue by wouterjsmit** [ProgrammingLife2016/PL2-2016#6]
The product vision should contain the following points.
1. Definition of the product
2. Problem that the product solves, including why it hasn't been solved yet.
3. Requirements Document
4. Expected problems / difficulties
5. Proposed solutions to these problems

**Comment by wouterjsmit** [comment]
First version (some parts are summarized only)
https://drive.google.com/drive/folders/0BxHb-G3M5qpQQ1FjWHJjSmZvUjg

**Comment by cbilstra** [comment]
Can we simply use a google docs document? Latex looks nice, but I cannot adjust anything right now.

**Comment by wouterjsmit** [comment]
Obviously. Alternative is to provide both the source .tex file and the output .pdf file.

I am going to finalize the document now, what changes did you have in mind? I can incorporate them right away

**Comment by wouterjsmit** [comment]
Moved to Milestone 2 since final deadline is only this Wednesday

**Comment by wouterjsmit** [comment]
@justinvdk collaborates
