### ISSUE TITLE
3rd party Annotations classes should be excluded from the analysis reports

### ISSUE THREAD

**Issue by wouterjsmit** [ProgrammingLife2016/PL2-2016#65]
As seen [here](https://github.com/ProgrammingLife2016/PL2-2016/pull/61/files/7379d18471027ab72704f905cc6aa19e9d0cfb9b#r62770976) in #61, we should simply exclude the 3rd party files from all analysis tools, because they are only a library that we use.
- [ ] Remove from PMD analysis
- [ ] Remove from Findbugs analysis
- [ ] Remove from Checkstyle analysis
- [ ] Remove from JaCoCo analysis

**Comment by cbilstra** [comment]
I agree
