### ISSUE TITLE
Checkstyle doesn't generate non-aggregate reports

### ISSUE THREAD

**Issue by cbilstra** [ProgrammingLife2016/PL2-2016#67]
Although checkstyle checks are performed, it does not seem to generate a report when performing a maven build with goal site.

**Comment by wouterjsmit** [comment]
See https://github.com/ProgrammingLife2016/PL2-2016/pull/54

**Comment by wouterjsmit** [comment]
Never mind, I was thinking about Cobertura

**Comment by wouterjsmit** [comment]
@cbilstra I do get an aggregate report in the PL2 (super) module.

I do not get non-aggregate reports in the separate sub modules. Is this what you mean?

**Comment by cbilstra** [comment]
@Pathemeous yes, that's what I mean.
