### ISSUE TITLE
Testing document should be updated, as well as Architecture Design

### ISSUE THREAD

**Issue by wouterjsmit** [ProgrammingLife2016/PL2-2016#72]
The testing document should be updated to include newly added special cases, or remove untested code that now has been tested.

Also, the testing document contains some information regarding the Architecture Design (module definition). We should update the architecture design to (also) contain this information and in general elaborate more using the current architecture.

**Comment by FarisElghlan** [comment]
Will do this tomorrow, so I can include todays changes.

**Comment by wouterjsmit** [comment]
@FarisElghlan Are you still able to do this?

**Comment by FarisElghlan** [comment]
Was actually only referring to the testing document (didn't notice the architecture was also in the title)...
See: #79
