### ISSUE TITLE
Parser should filter out any extra entries in the Phylogenetic Tree

### ISSUE THREAD

**Issue by wouterjsmit** [ProgrammingLife2016/PL2-2016#75]
The phylogenetic tree can contain more genomes than exist in the sequence graph.

The application uses the entries in the phylogenetic tree to select parts of the sequence graph. If the user can select elements that are not included in the graph, the application breaks (and should break).

During parsing, the phylogenetic tree should be checked for invalid entries and these should not be exposed to the user.

**Comment by FarisElghlan** [comment]
With the current codebase this is very easy to implement. The code written by @cathmer basically already does this. Will fix it this sprint.

**Comment by FarisElghlan** [comment]
Fixed, see: e48b799.
