### ISSUE TITLE
Bubbles Need Unique ID that works for alignment of subgraphs

### ISSUE THREAD

**Issue by wouterjsmit** [ProgrammingLife2016/PL2-2016#76]
The bubble ID should be a sophisticated system.

Discussion mainly between @FarisElghlan, @cathmer and @cbilstra.

See https://github.com/ProgrammingLife2016/PL2-2016/issues/24 for details.

**Comment by wouterjsmit** [comment]
@FarisElghlan @cbilstra Can this be closed?

**Comment by FarisElghlan** [comment]
Yes, I think we will simply use nested nodes for bubbles and don't use the ID of a bubble for comparisons (the original graph consisting out of only nodes will be alligned and after that the bubbles will be made, so comparison is done before the bubbles are made). To make the IDs of bubbles unique I guess we could use negative numbers to generate IDs for bubbles instead (nodes never have negative IDs).

**Comment by wouterjsmit** [comment]
Closing then.
