### ISSUE TITLE
Time Scalability: Data parsing (and processing) in real time

### ISSUE THREAD

**Issue by wouterjsmit** [ProgrammingLife2016/PL2-2016#82]
## Introduction

One of the main goals of this project is to achieve a data parsing (and processing) system that is scalable. Scalable can be viewed in terms of space complexity and time complexity.
This issue looks at **time complexity**.

This issue serves as a central point of discussion any development that is related to this goal. Any thoughts, progress, benchmarks, analytics, pull requests or issues can be posted / linked here.
## Grand Goal

Currently, scalable time complexity means that the system is able to load a 6000 genome sequence graph in real time. This is the highest benchmark that the client has provided us. However, achieving this benchmark is not sufficient for complete scalability. Complete scalability means that the system will be able to load future data sets in real time as well. These data sets are estimated to grow explosively, with an expectation of a total of 60,000 genomes next year. This is a 1000% increase per year.
## Definition of 'Real time'

Because genome data sets are inherently large, dealing with the data is no trivial point. While 'real time' is often defined as _instantenous to the user_, we must therefore make a slight adjustment to this definition.

We allow for the data to be pre-processed (parsed, loaded in) at the start of the application. This may take more than minutes (but not hours if possible). Generally speaking, this step may take _reasonable_ time, which can be roughly translated as _as fast as possible within our capabilities, budget and schedule_.

The point of pre-processing is that it only happens once: at the start of the workflow. During any further use of the application, all interaction should provide an _instanteneous_ response. The pre-processing may take longer, if that is necessary to achieve this.

**Comment by wouterjsmit** [comment]
#81 creates a big leap in this goal.
@FarisElghlan also provided a benchmark and suggestions for future work regarding this problem in a [comment](https://github.com/ProgrammingLife2016/PL2-2016/pull/81#issuecomment-219294869).

Quoting him:

> Performance:
> First parsing the dataset of 10 genomes took around 2.5 seconds, now it takes around 100-120 milliseconds (20-25 times faster)
> First parsing the dataset of 328 genomes took around 3 minutes, now it takes around 1.5-1.7 seconds (105 times faster)
> 
> The algorithm has a time complexity of O(n) (lineair), so I expect the dataset of 6000 genomes to be loadable within 30 seconds (6000 / 328 \* 1.7 = 31 seconds).
> 
> Simply reading all of the lines of the file into java strings takes 0.5 seconds for the dataset of 328 genomes, so there is a possible performance gain of 1.7 / 0.5 = 3.4 times the current speed. This would however only be possible if reading the data from disk and processing it happens concurrently and the data processing is faster than the data reading. If we rewrite the parser in native C code and use multithreading to process the data while it is being read I guess we could possibly make it 2-3 times faster than it currently is. I don't think this is worth the effort, unless if we get much larger datasets which take a lot longer to load (for example more than 5 minutes).
> I assume we will only have to improve the performance of the parser if we get datasets of more than 60,000 genomes.

**Comment by FarisElghlan** [comment]
Improved the splitting algorithm. Splitting the main graph in subgraphs now takes about 300ms for the graph of  328 genomes (with a complexity of O(n) time), see commit: https://github.com/ProgrammingLife2016/PL2-2016/commit/8e3f81c017089cea1eb21a084cc6fd90e11900e3

**Comment by FarisElghlan** [comment]
Improved the graph comparison algorithm. Comparing two subgraphs now takes about 800ms for the graph of 328 genomes (with a complexity of O(n) time), see commit: https://github.com/ProgrammingLife2016/PL2-2016/commit/5701f07c65a822d8c06497e8952f1cc69a316c40

**Comment by FarisElghlan** [comment]
Improved the GUI performance. The GUI can now draw the graph in real time.
See commit: https://github.com/ProgrammingLife2016/PL2-2016/commit/15498186b27f39ed655f65c15475bf8a1089c30c
Instead of drawing the whole graph, only the part which is shown and 10 levels deep to the left and right are drawn. (the parts to the left/right are only drawn to show the edges, this can still be improved).

**Comment by wouterjsmit** [comment]
According to the feedback provided by the Programming Life team, we should not focus on improving this any further right now. Our implementation is way above expecations and focus should now be on other aspects of the application, such as semantic zoom and usability.
