### ISSUE TITLE
Model Classes must be refactored

### ISSUE THREAD

**Issue by wouterjsmit** [ProgrammingLife2016/PL2-2016#83]
The model classes leave a lot of room for (space complexity) optimization.

The classes are defined by wrong inheritance structures, violating the Liskov principle where some API should be provided by parents rather than children.
The API of some classes does not hide the class implementation (for instance exposing the inner datastructure with `OriginalGraph.getNodes()`.

Doing this is necessary for the code quality, but also to improve the space complexity, which is probably our only remaining problem in terms of data scalability.

**Comment by FarisElghlan** [comment]
Some of the model classes currently have low test coverage. Could you create an issue about this when you're done with the refactoring?

**Comment by wouterjsmit** [comment]
I will add tests wherever possible.

**Comment by wouterjsmit** [comment]
Since I am sick I will most likely not be able to finish this before 12:30 tomorrow. I will make sure to do it next iteration (which is also the version that we will deliver to SIG for software quality feedback).

**Comment by wouterjsmit** [comment]
Closed by #124
